from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import Protocol

from app.models.entities import (
    ClassRecord,
    FaceEmbeddingRecord,
    MealEntryRecord,
    MealType,
    RecognitionAttemptRecord,
    StudentRecord,
    SchoolYear,
    UserRecord,
    UserRole,
)


@dataclass(slots=True)
class MealEntryFilters:
    date: date | None = None
    class_id: str | None = None
    student_id: str | None = None
    meal_type: MealType | None = None


class UserRepository(Protocol):
    def list_users(self) -> list[UserRecord]: ...
    def get_by_id(self, user_id: str) -> UserRecord | None: ...
    def get_by_username(self, username: str) -> UserRecord | None: ...
    def create(self, user: UserRecord) -> UserRecord: ...
    def update(self, user: UserRecord) -> UserRecord: ...
    def delete(self, user_id: str) -> None: ...


class RoleRepository(Protocol):
    def list_roles(self) -> list[UserRole]: ...
    def exists(self, role: UserRole) -> bool: ...


class ClassRepository(Protocol):
    def list_classes(self) -> list[ClassRecord]: ...
    def get_by_id(self, class_id: str) -> ClassRecord | None: ...
    def get_by_name(self, name: str, school_year: SchoolYear | None = None) -> ClassRecord | None: ...
    def create(self, class_record: ClassRecord) -> ClassRecord: ...
    def update(self, class_record: ClassRecord) -> ClassRecord: ...
    def delete(self, class_id: str) -> None: ...


class StudentRepository(Protocol):
    def list_students(self) -> list[StudentRecord]: ...
    def get_by_id(self, student_id: str) -> StudentRecord | None: ...
    def get_by_cpf(self, cpf: str) -> StudentRecord | None: ...
    def list_by_class_id(self, class_id: str) -> list[StudentRecord]: ...
    def create(self, student: StudentRecord) -> StudentRecord: ...
    def update(self, student: StudentRecord) -> StudentRecord: ...
    def delete(self, student_id: str) -> None: ...


class FaceEmbeddingRepository(Protocol):
    def list_embeddings(self) -> list[FaceEmbeddingRecord]: ...
    def get_by_student_id(self, student_id: str) -> FaceEmbeddingRecord | None: ...
    def upsert(self, embedding: FaceEmbeddingRecord) -> FaceEmbeddingRecord: ...
    def delete_by_student_id(self, student_id: str) -> None: ...


class MealEntryRepository(Protocol):
    def list_entries(self, filters: MealEntryFilters | None = None) -> list[MealEntryRecord]: ...
    def create(self, entry: MealEntryRecord) -> MealEntryRecord: ...
    def delete_by_student_id(self, student_id: str) -> None: ...


class RecognitionAttemptRepository(Protocol):
    def list_attempts(self) -> list[RecognitionAttemptRecord]: ...
    def create(self, attempt: RecognitionAttemptRecord) -> RecognitionAttemptRecord: ...
    def delete_by_student_id(self, student_id: str) -> None: ...
